version: "3.8"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: php:8.3.3-fpm
        container_name: guestbook-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - guestbook-network
    db:
        image: mysql:8.0
        container_name: guestbook-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3306:3306
        networks:
            - guestbook-network
    nginx:
        image: nginx:alpine
        container_name: guestbook-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./nginx/:/etc/nginx/conf.d/
        networks:
            - guestbook-network
networks:
    guestbook-network:
        driver: bridge
